name: arabic_search
description: Arabic-first text normalization, digit conversion, and search-key utilities for fast & accurate Arabic search/filtering.
version: 0.1.0
homepage: https://github.com/OmarAbdelAziz123/arabic_search

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  meta: ^1.11.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0