name: arabic_search
description: >
  Arabic-first text normalization and search utilities for Dart & Flutter,
  with robust normalization, token-based search, and simple result ranking.

version: 0.2.3
homepage: https://github.com/OmarAbdelAziz123/arabic_search

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  meta: ^1.11.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0